booksChaptersApp/urls.py

from django.urls import path

from . import views

urlpatterns = [
    path('test/', views.testing_view),
]

django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('booksChaptersApp.urls'))
]

booksChaptersApp/models.py
# myApp/models.py
from django.db import models


# Create your models here.
# books table #
class books_DB(models.Model):
  #pk is book_id
  book_id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
  book_name = models.CharField(max_length=100)

# chapters table #
class chapters_DB(models.Model):
  #pk is chapter_id
  chapter_id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
  #foreign key 'book_id' from 'books_DB' 
  book_id = models.ForeignKey(books_DB, on_delete=models.CASCADE, default=None)
  chapter_name = models.CharField(max_length=100)

booksChaptersApp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.template import loader
from .models import *


def testing_view(request):
  books_DB_all = books_DB.objects.all()

  template = loader.get_template('debug_template.html')
  context = {
    'all_books': books_DB_all,
  }
  return HttpResponse(template.render(context, request))

templates/debug_template.html
<!DOCTYPE html>
<html>
<body>

{{ all_textbooks }}

<ul class="books">

    <!-- all_books is books_DB.objects.all() -->
    {% for x in all_books %}
    <li class="book">
    <p>{{ x.book_name }}</p>
    <ol class="chapters">
        {% for y in x.chapters_db_set.all  %}
            <li class="chapter">{{ y.chapter_name }}</li>
        {% endfor %}
    </ol>
    {% endfor %}
    </li>
</ul>

<p>Debug template</p>

</body>
</html>